name: picbudget_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  liquid_swipe: ^3.1.0
  lottie: ^3.1.2
  path: ^1.9.0
  string_extensions: ^0.7.1
  transitioned_indexed_stack: ^1.0.2

flutter_native_splash:
  color: "#1A1A1A"
  image: assets/images/splash.png
  android: true
  android_12:
    color: "#1A1A1A"
    image: assets/images/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/splash.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/lottie/
